/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Crowdfunding {
  export type TierStruct = {
    name: string;
    amount: BigNumberish;
    backers: BigNumberish;
  };

  export type TierStructOutput = [
    name: string,
    amount: bigint,
    backers: bigint
  ] & { name: string; amount: bigint; backers: bigint };
}

export interface CrowdfundingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTier"
      | "backers"
      | "campaignStatus"
      | "deadline"
      | "description"
      | "fund"
      | "getBackersTotalContribution"
      | "getCampaignStatus"
      | "getContractBalance"
      | "getTiers"
      | "goal"
      | "hasFundedTier"
      | "isCampaignPaused"
      | "name"
      | "owner"
      | "pauseCampaign"
      | "refund"
      | "removeTier"
      | "resumeCampaign"
      | "tiers"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addTier",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "backers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignStatus",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deadline", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fund", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getBackersTotalContribution",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getTiers", values?: undefined): string;
  encodeFunctionData(functionFragment: "goal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasFundedTier",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isCampaignPaused",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseCampaign",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "refund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resumeCampaign",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tiers", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addTier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "backers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "campaignStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deadline", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBackersTotalContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTiers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "goal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasFundedTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCampaignPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resumeCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tiers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export interface Crowdfunding extends BaseContract {
  connect(runner?: ContractRunner | null): Crowdfunding;
  waitForDeployment(): Promise<this>;

  interface: CrowdfundingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTier: TypedContractMethod<
    [_name: string, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  backers: TypedContractMethod<
    [arg0: AddressLike],
    [[string, bigint] & { backer: string; totalContribution: bigint }],
    "view"
  >;

  campaignStatus: TypedContractMethod<[], [bigint], "view">;

  deadline: TypedContractMethod<[], [bigint], "view">;

  description: TypedContractMethod<[], [string], "view">;

  fund: TypedContractMethod<[_tierIndex: BigNumberish], [void], "payable">;

  getBackersTotalContribution: TypedContractMethod<
    [_backer: AddressLike],
    [bigint],
    "view"
  >;

  getCampaignStatus: TypedContractMethod<[], [bigint], "view">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getTiers: TypedContractMethod<[], [Crowdfunding.TierStructOutput[]], "view">;

  goal: TypedContractMethod<[], [bigint], "view">;

  hasFundedTier: TypedContractMethod<
    [_backer: AddressLike, _tierIndex: BigNumberish],
    [boolean],
    "view"
  >;

  isCampaignPaused: TypedContractMethod<[], [boolean], "view">;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pauseCampaign: TypedContractMethod<[], [void], "nonpayable">;

  refund: TypedContractMethod<[], [void], "nonpayable">;

  removeTier: TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;

  resumeCampaign: TypedContractMethod<[], [void], "nonpayable">;

  tiers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        name: string;
        amount: bigint;
        backers: bigint;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTier"
  ): TypedContractMethod<
    [_name: string, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "backers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [[string, bigint] & { backer: string; totalContribution: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaignStatus"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "description"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[_tierIndex: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getBackersTotalContribution"
  ): TypedContractMethod<[_backer: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCampaignStatus"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTiers"
  ): TypedContractMethod<[], [Crowdfunding.TierStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "goal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasFundedTier"
  ): TypedContractMethod<
    [_backer: AddressLike, _tierIndex: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCampaignPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pauseCampaign"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeTier"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resumeCampaign"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tiers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        name: string;
        amount: bigint;
        backers: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
